### ISSUE TITLE
færre cards vist på mobil

### ISSUE THREAD

**Issue by Siggik** [dukop/django-dukop#102]
Blir lidt uoverskueligt med meget langt scroll.

**Comment by Siggik** [comment]
I will suggest the same one desktop, or another solution to avoid to much scrolling. Maybe 8 insted of 17?

**Comment by benjaoming** [comment]
Yes, if we can keep the functionality of desktop and mobile 1:1 that'd be great. I think that 8 cards sounds good!

**Comment by benjaoming** [comment]
Fixed in #284
