### ISSUE TITLE
oprettelser af bruger går direkte til oprettelse af event. 

### ISSUE THREAD

**Issue by Siggik** [dukop/django-dukop#112]
Jeg lykkedes fint med at oprette bruger og få til sendt token på email. Men jeg nåede at ret langt ned i den formular der kom op på skærmen, før jeg fattede at jeg ikke skrev detaljer om min bruger, men var ved at oprette event. Jeg kunne heller ikke finde en side, hvor jeg kunne se og redigerer min bruger.

**Comment by benjaoming** [comment]
Er dette stadig relevant?

**Comment by Siggik** [comment]
Nej, det virker fint som det er nu.
