### ISSUE TITLE
A lot of events from the old site is not shown on the beta site.

### ISSUE THREAD

**Issue by Siggik** [dukop/django-dukop#147]
f.eks alle de her på 1. okt: 

12:00 Aktion Lützerath
Bygge Hygge Weekend-Offgrid ;) 16:00 Workshop Flydende by
Bogcaféen Halmtorvet fylder 6 år 17:00 Fest Andet Mad Bogcaféen Halmtorvet
Kom til møde i Solidaritetshuset , Situationen i Afghanistan 17:00 Møde Solidaritetsbutikken
ANOTHER WORLD IS NOW: Grand re-opening with the Zapatistas 18:00 Art Folkets Hus 1.sal
Something in need of Repair: Fumera + Konvoj + The Brotherhood of Sonic Love 19:30 Koncert Råhuset

**Comment by benjaoming** [comment]
Det er rettet nu - sync jobbet crashede pga fejl.
