### ISSUE TITLE
Sign-up w/o password

### ISSUE THREAD

**Issue by benjaoming** [dukop/django-dukop#15]
There has been a proposal that signing up should be possible to do w/o passwords.

Flow, sign-up:

* Create an account w/ some profile data.
* Receive an email for confirmation
* Click confirmation link

Flow login:

* Type in email
* See a screen w/ confirmation code input field
* Receive an email w/ confirmation code
* Copy 1-time code from email

Secondarily: You can always create or delete your password from your account.

Any suggestions for modifying this are most welcome

**Comment by benjaoming** [comment]
This is now being worked out in #13

**Comment by reynir** [comment]
Since #13 is now merged, is this now all implemented?

**Comment by benjaoming** [comment]
Yes, indeed, I looked over it again and I think it's mostly a matter now of refining stuff in case there's some issues making people understand how it works or why it's this way.

It should also perhaps have a security review.
