### ISSUE TITLE
The user that created the event should be visible on the event. 

### ISSUE THREAD

**Issue by Siggik** [dukop/django-dukop#160]

**Comment by Siggik** [comment]
Især for admin, men også for normale brugere.

Lige nu kan jeg slet ikke som normal brugere finde nogle brugerprofiler nogen steder. Jeg foreslår at det altid er vist på eventet, også selv om de ikke har valgt et navn, så kan der så stå "unnamed profile" eller "unavngiven profil"

Som admin, kan jeg se bruger profilerne, men hverken under brugerprofilerne eller under events kan jeg se hvem der har oprettet eventet. Det villle være meget gavnligt at kunne.

**Comment by benjaoming** [comment]
Fixed in #329
