### ISSUE TITLE
Displaying old events

### ISSUE THREAD

**Issue by Siggik** [dukop/django-dukop#22]
Det kunne være sejt, hvis alle kunne se gamle events. Eller hvad tænker i andre? Gir det mening og hvis, hvordan kan man implementere det i userfacen?  @tadoh @larsgaardsoe

**Comment by benjaoming** [comment]
Related: #73

**Comment by benjaoming** [comment]
Events should disappear after 6 months.

**Comment by benjaoming** [comment]
Because of copyright trolls, we are just going to have things up while they are relevant + 30 days lookback for some of the views. This is implemented across a lot of views and feeds.
