### ISSUE TITLE
url for each sphere

### ISSUE THREAD

**Issue by Siggik** [dukop/django-dukop#298]
Så sydfyn og Århus kan linke direkte til deres sfære.  Vi kunne også overveje om standarden skal fortsætte med at være københavn og skiftes til everywhere.

**Comment by benjaoming** [comment]
Det er muligt at kopiere links direkte:

https://beta.dukop.dk/en/sphere/change/3/

Men måske vi skulle lave et par subdomæner, der kører en redirect ala aarhus.dukop.dk => https://beta.dukop.dk/en/sphere/change/3/

**Comment by benjaoming** [comment]
https://sydfyn.dukop.dk/
https://aarhus.dukop.dk/
https://cph.dukop.dk/
