### ISSUE TITLE
event in happenning today, that happens the day after. 

### ISSUE THREAD

**Issue by Siggik** [dukop/django-dukop#342]
Why is the 1. maj event showed here? 

![signal-2022-04-30-113316_001](https://user-images.githubusercontent.com/7570153/166100267-ec69f151-8ce0-4d43-bdb0-5daf7441c843.jpeg)

**Comment by Siggik** [comment]
https://dukop.dk/en/event/anarkistisk-1-maj-ingen-kampdag-pa-tom-mave/4091/

**Comment by benjaoming** [comment]
I was just about to post this issue :)

It seems like something related to the event beginning at 8 AM the next day, not sure yet...
