### ISSUE TITLE
Im confused how to create an event and what the difference between log in and sign up is?

### ISSUE THREAD

**Issue by Siggik** [dukop/django-dukop#68]

**Comment by benjaoming** [comment]
There might be 2 issues here?

1. Advertising the ability to create events for users that are not logged in (but how?)
2. Writing more texts on Log In and Sign Up pages so it's clear that they are different. These two functions will become very different over time, and right now they might seem a bit similar.

**Comment by Siggik** [comment]
Could a solution be that "log in", is named "create event" instead, because that is what you need the log in to do?

**Comment by Siggik** [comment]
actually the same as the old site...

**Comment by benjaoming** [comment]
In the future, people can log in or sign up for 2 reasons:

* To create events
* To subscribe / unsubscribe / manage stuff

I think it might (which is also how the current site functions) that we should change the "Sign Up" to "Create Event" and then have that redirect to a page that says to either sign up or log in.

Will have a look!
