### ISSUE TITLE
Improve label of iCAL/ICS subscription label

### ISSUE THREAD

**Issue by benjaoming** [dukop/django-dukop#94]
"Feed subscription" might be hard to understand.

Related: Margins are really bad on mobile.

![image](https://user-images.githubusercontent.com/374612/121237889-cffccc00-c897-11eb-9c64-457968bf0e3f.png)

**Comment by Siggik** [comment]
Forslag fra kollektivet: ift. tekst, kan man måske skrive noge a la: 

"Vil du tilføje dukops event kalender til din google calender eller ical, kan du bruge dette link til at integrere"

...eller så noget... for jeg tror du har ret, det skal nok forklares hvad det kan og hvorfor man skal være interesseret i det

**Comment by Siggik** [comment]
Jeg tænker det. desuden kunne være godt med et link til guide forskellige guide til forskellige devices. Minimum Iphone og android. På Iphone er det i hvert fald ikke særligt intuitivt.
